// داده‌های نمونه کارجوها

export const jobSeekers = [
  {
    id: 1,
    firstName: "علی",
    lastName: "احمدی",
    jobTitle: "توسعه‌دهنده فول‌استک",
    city: "تهران",
    province: "تهران",
    profileImage:
      "https://images.unsplash.com/photo-1472099645785-6461ffad8d80?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80",
    lastExperience:
      "توسعه‌دهنده ارشد React در شرکت فناوری پارس با ۳ سال تجربه در پروژه‌های بزرگ",
    topSkills: [
      "React.js",
      "Node.js",
      "JavaScript",
      "TypeScript",
      "MongoDB",
      "Python",
    ],
    languages: [
      { language: "انگلیسی", proficiency: "پیشرفته" },
      { language: "عربی", proficiency: "متوسط" },
    ],
    expectedSalary: "15000000",
    profileViews: 156,
    lastUpdate: "۲ ساعت پیش",
    responseRate: 85,
    isBookmarked: false,
  },
  {
    id: 2,
    firstName: "فاطمه",
    lastName: "کریمی",
    jobTitle: "طراح UI/UX",
    city: "اصفهان",
    province: "اصفهان",
    profileImage:
      "https://images.unsplash.com/photo-1494790108755-2616b612b786?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80",
    lastExperience:
      "طراح رابط کاربری در استودیو کریتیو با تخصص در طراحی اپلیکیشن‌های موبایل",
    topSkills: ["Figma", "Adobe XD", "Sketch", "Prototyping", "User Research"],
    languages: [{ language: "انگلیسی", proficiency: "پیشرفته" }],
    expectedSalary: "12000000",
    profileViews: 89,
    lastUpdate: "۱ روز پیش",
    responseRate: 92,
    isBookmarked: true,
  },
  {
    id: 3,
    firstName: "محمد",
    lastName: "رضایی",
    jobTitle: "متخصص DevOps",
    city: "شیراز",
    province: "فارس",
    profileImage:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80",
    lastExperience:
      "مهندس DevOps در شرکت داده‌کاوان با تجربه در AWS و Kubernetes",
    topSkills: ["Docker", "Kubernetes", "AWS", "Jenkins", "Terraform", "Linux"],
    languages: [{ language: "انگلیسی", proficiency: "حرفه‌ای" }],
    expectedSalary: "18000000",
    profileViews: 203,
    lastUpdate: "۳ ساعت پیش",
    responseRate: 78,
    isBookmarked: false,
  },
  {
    id: 4,
    firstName: "زهرا",
    lastName: "محمدی",
    jobTitle: "تحلیلگر داده",
    city: "مشهد",
    province: "خراسان رضوی",
    profileImage:
      "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80",
    lastExperience:
      "تحلیلگر داده در بانک ملی با تخصص در یادگیری ماشین و تجزیه و تحلیل داده",
    topSkills: [
      "Python",
      "R",
      "SQL",
      "Machine Learning",
      "Tableau",
      "Power BI",
    ],
    languages: [
      { language: "انگلیسی", proficiency: "پیشرفته" },
      { language: "فرانسوی", proficiency: "متوسط" },
    ],
    expectedSalary: "14000000",
    profileViews: 127,
    lastUpdate: "۵ ساعت پیش",
    responseRate: 88,
    isBookmarked: false,
  },
  {
    id: 5,
    firstName: "حسین",
    lastName: "نوری",
    jobTitle: "مهندس نرم‌افزار موبایل",
    city: "تبریز",
    province: "آذربایجان شرقی",
    profileImage:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80",
    lastExperience:
      "توسعه‌دهنده اپلیکیشن موبایل در استارتاپ تکنولوژی با تجربه Flutter و React Native",
    topSkills: [
      "Flutter",
      "React Native",
      "Dart",
      "JavaScript",
      "Firebase",
      "iOS",
    ],
    languages: [{ language: "انگلیسی", proficiency: "پیشرفته" }],
    expectedSalary: "13000000",
    profileViews: 94,
    lastUpdate: "۱ روز پیش",
    responseRate: 81,
    isBookmarked: true,
  },
  {
    id: 6,
    firstName: "مریم",
    lastName: "صادقی",
    jobTitle: "مدیر محصول",
    city: "کرج",
    province: "البرز",
    profileImage:
      "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80",
    lastExperience:
      "مدیر محصول در شرکت فناوری نوآوران با تجربه راه‌اندازی ۵ محصول موفق",
    topSkills: [
      "Product Management",
      "Agile",
      "Scrum",
      "User Research",
      "Analytics",
      "Strategy",
    ],
    languages: [
      { language: "انگلیسی", proficiency: "حرفه‌ای" },
      { language: "آلمانی", proficiency: "متوسط" },
    ],
    expectedSalary: "20000000",
    profileViews: 178,
    lastUpdate: "۴ ساعت پیش",
    responseRate: 95,
    isBookmarked: false,
  },
  {
    id: 7,
    firstName: "امیر",
    lastName: "حسینی",
    jobTitle: "مهندس امنیت سایبری",
    city: "تهران",
    province: "تهران",
    profileImage:
      "https://images.unsplash.com/photo-1519085360753-b8d87734a5a2?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80",
    lastExperience:
      "متخصص امنیت سایبری در بانک مرکزی با تجربه در حفاظت از زیرساخت‌های حیاتی",
    topSkills: [
      "Cybersecurity",
      "Penetration Testing",
      "Network Security",
      "CISSP",
      "Ethical Hacking",
      "Firewall",
    ],
    languages: [
      { language: "انگلیسی", proficiency: "حرفه‌ای" },
      { language: "روسی", proficiency: "متوسط" },
    ],
    expectedSalary: "22000000",
    profileViews: 245,
    lastUpdate: "۱ ساعت پیش",
    responseRate: 90,
    isBookmarked: false,
  },
  {
    id: 8,
    firstName: "نگار",
    lastName: "موسوی",
    jobTitle: "مهندس یادگیری ماشین",
    city: "اصفهان",
    province: "اصفهان",
    profileImage:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80",
    lastExperience:
      "محقق یادگیری ماشین در مرکز تحقیقات فناوری با انتشار ۱۰ مقاله علمی",
    topSkills: [
      "Machine Learning",
      "Deep Learning",
      "TensorFlow",
      "PyTorch",
      "Computer Vision",
      "NLP",
    ],
    languages: [
      { language: "انگلیسی", proficiency: "حرفه‌ای" },
      { language: "فرانسوی", proficiency: "پیشرفته" },
    ],
    expectedSalary: "25000000",
    profileViews: 312,
    lastUpdate: "۳ ساعت پیش",
    responseRate: 87,
    isBookmarked: true,
  },
  {
    id: 9,
    firstName: "رضا",
    lastName: "کاظمی",
    jobTitle: "معمار نرم‌افزار",
    city: "شیراز",
    province: "فارس",
    profileImage:
      "https://images.unsplash.com/photo-1560250097-0b93528c311a?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80",
    lastExperience:
      "معمار نرم‌افزار ارشد در شرکت تکنولوژی پیشرو با طراحی سیستم‌های مقیاس‌پذیر",
    topSkills: [
      "System Architecture",
      "Microservices",
      "Cloud Computing",
      "Scalability",
      "Design Patterns",
      "API Design",
    ],
    languages: [{ language: "انگلیسی", proficiency: "حرفه‌ای" }],
    expectedSalary: "28000000",
    profileViews: 189,
    lastUpdate: "۶ ساعت پیش",
    responseRate: 93,
    isBookmarked: false,
  },
  {
    id: 10,
    firstName: "سارا",
    lastName: "جعفری",
    jobTitle: "متخصص بازاریابی دیجیتال",
    city: "مشهد",
    province: "خراسان رضوی",
    profileImage:
      "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80",
    lastExperience:
      "مدیر بازاریابی دیجیتال در آژانس تبلیغاتی با موفقیت در کمپین‌های ملی",
    topSkills: [
      "Digital Marketing",
      "SEO/SEM",
      "Social Media",
      "Google Analytics",
      "Content Strategy",
      "PPC",
    ],
    languages: [
      { language: "انگلیسی", proficiency: "پیشرفته" },
      { language: "ترکی", proficiency: "متوسط" },
    ],
    expectedSalary: "16000000",
    profileViews: 134,
    lastUpdate: "۴ ساعت پیش",
    responseRate: 89,
    isBookmarked: false,
  },
  {
    id: 11,
    firstName: "کامران",
    lastName: "عباسی",
    jobTitle: "مهندس بلاک‌چین",
    city: "تبریز",
    province: "آذربایجان شرقی",
    profileImage:
      "https://images.unsplash.com/photo-1472099645785-6461ffad8d80?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80",
    lastExperience:
      "توسعه‌دهنده بلاک‌چین در استارتاپ فین‌تک با تجربه در ارزهای دیجیتال",
    topSkills: [
      "Blockchain",
      "Solidity",
      "Ethereum",
      "Smart Contracts",
      "Web3",
      "Cryptocurrency",
    ],
    languages: [{ language: "انگلیسی", proficiency: "پیشرفته" }],
    expectedSalary: "30000000",
    profileViews: 267,
    lastUpdate: "۲ ساعت پیش",
    responseRate: 82,
    isBookmarked: true,
  },
  {
    id: 12,
    firstName: "لیلا",
    lastName: "رستمی",
    jobTitle: "مهندس کیفیت نرم‌افزار",
    city: "کرج",
    province: "البرز",
    profileImage:
      "https://images.unsplash.com/photo-1580489944761-15a19d654956?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80",
    lastExperience: "مهندس QA ارشد در شرکت نرم‌افزاری با تخصص در تست اتوماسیون",
    topSkills: [
      "Software Testing",
      "Test Automation",
      "Selenium",
      "JIRA",
      "API Testing",
      "Performance Testing",
    ],
    languages: [{ language: "انگلیسی", proficiency: "پیشرفته" }],
    expectedSalary: "14000000",
    profileViews: 98,
    lastUpdate: "۱ روز پیش",
    responseRate: 91,
    isBookmarked: false,
  },
  {
    id: 13,
    firstName: "بهزاد",
    lastName: "قاسمی",
    jobTitle: "مهندس شبکه",
    city: "اهواز",
    province: "خوزستان",
    profileImage:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80",
    lastExperience:
      "مهندس شبکه در شرکت مخابرات با تجربه در طراحی و پیاده‌سازی شبکه‌های پیچیده",
    topSkills: [
      "Network Engineering",
      "Cisco",
      "CCNP",
      "Routing & Switching",
      "Network Security",
      "MPLS",
    ],
    languages: [{ language: "انگلیسی", proficiency: "متوسط" }],
    expectedSalary: "17000000",
    profileViews: 145,
    lastUpdate: "۷ ساعت پیش",
    responseRate: 86,
    isBookmarked: false,
  },
  {
    id: 14,
    firstName: "شیدا",
    lastName: "نوروزی",
    jobTitle: "طراح گرافیک",
    city: "ساری",
    province: "مازندران",
    profileImage:
      "https://images.unsplash.com/photo-1494790108755-2616b612b786?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80",
    lastExperience:
      "طراح گرافیک خلاق در آژانس تبلیغاتی با پورتفولیو قوی در برندسازی",
    topSkills: [
      "Graphic Design",
      "Adobe Creative Suite",
      "Branding",
      "Logo Design",
      "Print Design",
      "Typography",
    ],
    languages: [
      { language: "انگلیسی", proficiency: "پیشرفته" },
      { language: "ایتالیایی", proficiency: "مبتدی" },
    ],
    expectedSalary: "11000000",
    profileViews: 76,
    lastUpdate: "۵ ساعت پیش",
    responseRate: 94,
    isBookmarked: false,
  },
  {
    id: 15,
    firstName: "آرش",
    lastName: "میرزایی",
    jobTitle: "مهندس سخت‌افزار",
    city: "کرمان",
    province: "کرمان",
    profileImage:
      "https://images.unsplash.com/photo-1472099645785-6461ffad8d80?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80",
    lastExperience:
      "مهندس سخت‌افزار در شرکت الکترونیک با تخصص در طراحی مدارات دیجیتال",
    topSkills: [
      "Hardware Engineering",
      "PCB Design",
      "Embedded Systems",
      "FPGA",
      "Circuit Design",
      "Microcontrollers",
    ],
    languages: [{ language: "انگلیسی", proficiency: "پیشرفته" }],
    expectedSalary: "19000000",
    profileViews: 112,
    lastUpdate: "۸ ساعت پیش",
    responseRate: 88,
    isBookmarked: false,
  },
];
export const categories = [
  { value: "all", label: "همه دسته‌ها" },
  { value: "frontend", label: "فرانت‌اند" },
  { value: "backend", label: "بک‌اند" },
  { value: "fullstack", label: "فول‌استک" },
  { value: "mobile", label: "موبایل" },
  { value: "design", label: "طراحی" },
  { value: "data", label: "داده" },
  { value: "devops", label: "DevOps" },
  { value: "product", label: "مدیریت محصول" },
];
export const provinces = [
  { value: "all", label: "همه استان‌ها" },
  { value: "تهران", label: "تهران" },
  { value: "اصفهان", label: "اصفهان" },
  { value: "فارس", label: "فارس" },
  { value: "خراسان رضوی", label: "خراسان رضوی" },
  { value: "آذربایجان شرقی", label: "آذربایجان شرقی" },
  { value: "البرز", label: "البرز" },
  { value: "خوزستان", label: "خوزستان" },
  { value: "مازندران", label: "مازندران" },
];
export const locations = [
  { value: "all", label: "همه شهرها" },
  { value: "تهران", label: "تهران" },
  { value: "اصفهان", label: "اصفهان" },
  { value: "شیراز", label: "شیراز" },
  { value: "مشهد", label: "مشهد" },
  { value: "تبریز", label: "تبریز" },
  { value: "کرج", label: "کرج" },
];
export const sortOptions = [
  { value: "recent", label: "جدیدترین" },
  { value: "popular", label: "محبوب‌ترین" },
  { value: "experience", label: "بیشترین تجربه" },
  { value: "salary", label: "حقوق" },
];
// داده‌های نمونه رزومه (در واقعیت از API یا دیتابیس دریافت می‌شود)
export const resumeData = {
  basicInfo: {
    firstName: "علی",
    lastName: "احمدی",
    mobile: "09123456789",
    email: "ali.ahmadi@example.com",
  },
  profileImage:
    "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
  residence: {
    province: "تهران",
    city: "تهران",
    address: "خیابان ولیعصر، پلاک ۱۲۳",
  },
  jobInfo: {
    jobTitle: "توسعه‌دهنده فول‌استک",
    showSalary: true,
    salaryType: "amount",
    salaryAmount: "15000000",
  },
  workExperiences: [
    {
      companyName: "شرکت فناوری پارس",
      position: "توسعه‌دهنده ارشد React",
      startDate: "1401/03/15",
      endDate: "",
      currentJob: true,
      responsibilities:
        "توسعه و نگهداری اپلیکیشن‌های وب با React و Node.js، همکاری با تیم طراحی UI/UX، بهینه‌سازی عملکرد اپلیکیشن‌ها",
    },
    {
      companyName: "استودیو طراحی نوین",
      position: "برنامه‌نویس فرانت‌اند",
      startDate: "1399/06/10",
      endDate: "1401/02/28",
      currentJob: false,
      responsibilities:
        "پیاده‌سازی رابط کاربری وب‌سایت‌ها با HTML، CSS و JavaScript، همکاری با تیم بک‌اند برای یکپارچه‌سازی API",
    },
  ],
  skills: [
    { skillName: "React.js", proficiency: "حرفه‌ای" },
    { skillName: "Node.js", proficiency: "پیشرفته" },
    { skillName: "JavaScript", proficiency: "حرفه‌ای" },
    { skillName: "TypeScript", proficiency: "پیشرفته" },
    { skillName: "Python", proficiency: "متوسط" },
    { skillName: "MongoDB", proficiency: "پیشرفته" },
  ],
  languages: [
    { language: "انگلیسی", proficiency: "پیشرفته" },
    { language: "عربی", proficiency: "متوسط" },
  ],
  certificates: [
    {
      title: "گواهینامه React Developer",
      issuer: "Meta",
      certificateNumber: "RD-2023-001",
      link: "https://example.com/certificate",
      issueDate: "1402/05/15",
      expiryDate: "",
      noExpiry: true,
      description: "گواهینامه تخصصی توسعه اپلیکیشن با React",
    },
    {
      title: "AWS Cloud Practitioner",
      issuer: "Amazon Web Services",
      certificateNumber: "AWS-CP-2023",
      link: "https://example.com/aws-cert",
      issueDate: "1402/08/20",
      expiryDate: "1405/08/20",
      noExpiry: false,
      description: "گواهینامه مبانی خدمات ابری آمازون",
    },
  ],
  portfolioLink: "https://ali-ahmadi-portfolio.com",
  portfolioFiles: ["project1.pdf", "project2.pdf", "design-samples.zip"],
};
